In [1]:
import numpy as np

In [3]:
a = np.array([[12, 7, 21, 31, 11], [45, -2, 14, 27, 19], [-3, 15, 36, 71, 26], [4, -13, 55, 34, 15]])
w = np.array([1, 2, 1, 0, 0])

In [12]:
print(a.dot(w[:, np.newaxis]))

[[47]
 [55]
 [63]
 [33]]


In [16]:
print(w[:, np.newaxis])
print(w[np.newaxis, :])
print(w)
print(a)

[[1]
 [2]
 [1]
 [0]
 [0]]
[[1 2 1 0 0]]
[1 2 1 0 0]
[[ 12   7  21  31  11]
 [ 45  -2  14  27  19]
 [ -3  15  36  71  26]
 [  4 -13  55  34  15]]


In [18]:
a = np.array([[1, 2], [0, 1], [10, 0]])
b = np.array([[1, 0, 0], [0, 0, 2]])

In [23]:
c = np.dot(a, b)
print("a:\n",a)
print("b:\n",b)
print("c:\n",c)

a:
 [[ 1  2]
 [ 0  1]
 [10  0]]
b:
 [[1 0 0]
 [0 0 2]]
c:
 [[ 1  0  4]
 [ 0  0  2]
 [10  0  0]]


In [25]:
print(np.transpose(a))

[[ 1  0 10]
 [ 2  1  0]]


In [27]:
print(np.rank(a))

2


In [31]:
b = np.eye(2, 3)
print(b)

[[1. 0. 0.]
 [0. 1. 0.]]


In [39]:
e = np.eye((4, 5))
print(e)

TypeError: 'tuple' object cannot be interpreted as an integer

In [37]:
a = np.eye(4, 5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [36]:
a[[0, 3], [1, 3]]

array([0., 1.])