#Выбор семейства распределений в наивном байесе

In [11]:
from sklearn import datasets, metrics
from sklearn.model_selection import cross_val_score
from sklearn.naive_bayes import BernoulliNB, MultinomialNB, GaussianNB
import numpy as np

In [12]:
digits = datasets.load_digits()
breast_cancer = datasets.load_breast_cancer()

In [13]:
X_digits = digits.data
y_digits = digits.target

In [14]:
X_cancer = breast_cancer.data
y_cancer = breast_cancer.target

In [22]:
print(cross_val_score(BernoulliNB(), X_cancer, y_cancer).mean())
print(cross_val_score(MultinomialNB(), X_cancer, y_cancer).mean())
print(cross_val_score(GaussianNB(), X_cancer, y_cancer).mean())

0.6274204028589994
0.8945790401930752
0.9367492806089297


In [23]:
print(cross_val_score(BernoulliNB(), X_digits, y_digits).mean())
print(cross_val_score(MultinomialNB(), X_digits, y_digits).mean())
print(cross_val_score(GaussianNB(), X_digits, y_digits).mean())

0.8258236507780582
0.8708771489735053
0.8186003803550138


In [24]:
print(X_digits)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]


In [25]:
print(X_cancer)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
